A tensor is a multi-dimensional array of numerical values. Tensor computation (like numpy) with strong GPU acceleration.<br/>

**1️⃣N-d Tensor:**
- `0-dimensional (Scalar):` A single number, e.g., 5, 3.14, -10. A <font color='red'><b>scalar</b></font> is a single number and in tensor-speak it's a zero dimension tensor.
- `1-dimensional (Vector):` A list of numbers, e.g., [1, 2, 3]. A <font color='blue'><b>vector</b></font> is a single dimension tensor but can contain many numbers.<br/>
- `2-dimensional (Matrix):` A table of numbers, e.g., [[1, 2], [3, 4]]. <font color='green'><b>MATRIX</b></font>  has two dimensions.
- `3-dimensional (or higher):` Like a "cube" of numbers or more complex higher-dimensional structures. These are common for representing images, videos, and more.

**2️⃣Tensor datatypes:**<br/>
There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types). Some are specific for CPU and some are better for GPU.<br/>
Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).<br/>
The most common type (and generally the default) is `torch.float32` or `torch.float`.<br/>

**3️⃣Getting information from tensors:**<br/>
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

**4️⃣Math Operations:**<br/>
* Addition ⇒ `a+b `or `torh.add(a, b)`
* Substraction ⇒ `a-b `or `torh.sub(a, b)`
* Multiplication (element-wise) ⇒ `a*b `
* Division ⇒ `a/b `or `torh.div(a, b)`
* Matrix multiplication ⇒ "`@`" in Python is the symbol for matrix multiplication. [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) or [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html)
  
**5️⃣Special Arrays**<br/>
- zeros
- ones
- empty
- eye
- full<br/>

Using [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

**6️⃣Random Arrays**
- `torch.rand:` Create a n*m tensor filled with random numbers from a uniform distribution on the interval [0, 1)
- `torch.randn:` Create a n*m tensor filled with random numbers from a normal distribution with mean 0 and variance 1. 
- `torch.randint:` Create a n*m tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).
  
**7️⃣Indexing & Slicing**
- `Indexing`
  - Accessing individual elements:  use integer indices to specify the position of the element you want to retrieve.
- `Slicing`
  - Extracting sub-tensors: Slicing allows you to extract a sub-part of your tensor by specifying a range of indices using the colon : operator.
    - `start:end` (exclusive end)
    - `start:` (from start to end of dimension)
    - `:end` (from beginning to end of dimension)
    - `:` (all elements)
    - `start:end:step` (start to end with given step)
  - Slicing with steps: You can include a step to skip elements in the slice. `start:end:step`

**8️⃣`Unsqueeze & unsqueeze:`**
- The squeeze() method removes all singleton dimensions from a tensor. It will reduce the number of dimensions by removing the ones that have a size of 1.
- The unsqueeze() method adds a singleton dimension at a specified position in a tensor. It will increase the number of dimensions by adding a size of 1 dimension at a specific position.

In [22]:
import torch  #  torch.__version__  -> '2.5.1+cpu'

**Scalar, Vector, Column vector, Matrix, & N-d Tensor**


In [4]:
# Creating a 0D tensor (Scalar)
torch.tensor(4/3)

tensor(1.3333)

In [5]:
# Creating a 1D tensor (Vector)
a = torch.tensor([1, 2, 3])
print(f"{a = } --> {a.__class__ = }")

a = tensor([1, 2, 3]) --> a.__class__ = <class 'torch.Tensor'>


In [23]:
# Creating a 2D tensor (Column vector)
torch.tensor([[1], [2], [3], [4]])

tensor([[1],
        [2],
        [3],
        [4]])

In [24]:
# Creating a 2D tensor (Matrix)
torch.tensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
# Creating a 3D tensor
torch.tensor(
    [[[1, 2, 2 , 5],
      [3, 4, 0 , 8]],

     [[5, 6, 6, 7],
      [4, 8, 1, 2]],

     [[1, 1, 8, 9],
      [0, 0, 2, 3]]]
    )

tensor([[[1, 2, 2, 5],
         [3, 4, 0, 8]],

        [[5, 6, 6, 7],
         [4, 8, 1, 2]],

        [[1, 1, 8, 9],
         [0, 0, 2, 3]]])

In [27]:
# Creating a 4D tensor (Matrix)
torch.tensor(
    [[[[1, 2, 5, 4],
       [3, 4, 1, 0]],
      [[5, 6, 2, 3],
       [7, 8, 6, 4]]]]
    )

tensor([[[[1, 2, 5, 4],
          [3, 4, 1, 0]],

         [[5, 6, 2, 3],
          [7, 8, 6, 4]]]])

**Getting information from tensors:**

In [30]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([1.0, 5.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.dtype, float_32_tensor.device

(torch.float32, device(type='cpu'))

In [29]:
# Creating a 0D tensor (Scalar)
a = torch.tensor(4/3, dtype=torch.float64, device="cpu")
print(f"{a = } --> {a.shape = } --> {a.ndim = } --> {a.size() = }")
a.type(torch.float16)     # Convert into float16 or a.short()

a = tensor(1.3333, dtype=torch.float64) --> a.shape = torch.Size([]) --> a.ndim = 0 --> a.size() = torch.Size([])


tensor(1.3330, dtype=torch.float16)

In [31]:
a = tuple([(1, 2), (3, 4), (5, 6)])
torch.tensor(a)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [32]:
# Creating a 2D tensor (Matrix)
a = torch.tensor(
    [[[[1, 2],
       [3, 4]],
      [[5, 6],
       [7, 8]]],
     [[[9, 10],
       [11, 12]],
      [[13, 14],
       [15, 16]]]]
    )
print(f"{a = }\n{a.shape = } --> {a.ndim = } --> {a.size() = }")

a = tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
a.shape = torch.Size([2, 2, 2, 2]) --> a.ndim = 4 --> a.size() = torch.Size([2, 2, 2, 2])


**Math Operations**

In [57]:
#  Mean, std
a = torch.tensor([1, 2, 3])
a.float().mean(), a.type(torch.float32).std()

(tensor(2.), tensor(1.))

In [33]:
# Creating a 2D tensor (Matrix)
a = torch.tensor(
    [[[[1, 2],
       [3, 4]],
      [[5, 6],
       [7, 8]]],
     [[[9, 10],
       [11, 12]],
      [[13, 14],
       [15, 16]]]]
    )
a = a.T
print(f"{a = }\n{a.shape = } --> {a.ndim = } --> {a.size() = }")

a = tensor([[[[ 1,  9],
          [ 5, 13]],

         [[ 3, 11],
          [ 7, 15]]],


        [[[ 2, 10],
          [ 6, 14]],

         [[ 4, 12],
          [ 8, 16]]]])
a.shape = torch.Size([2, 2, 2, 2]) --> a.ndim = 4 --> a.size() = torch.Size([2, 2, 2, 2])


In [60]:
a = torch.randint(10, (2, 2))
b = torch.randint(10, (2, 2))
a, b

(tensor([[1, 5],
         [7, 3]]),
 tensor([[8, 9],
         [6, 9]]))

In [64]:
torch.add(a, b, ), torch.sub(a, b, )

(tensor([[ 9, 14],
         [13, 12]]),
 tensor([[-7, -4],
         [ 1, -6]]))

In [65]:
a * b, a @ b, torch.matmul(a, b)

(tensor([[ 8, 45],
         [42, 27]]),
 tensor([[38, 54],
         [74, 90]]),
 tensor([[38, 54],
         [74, 90]]))

In [66]:
a / b

tensor([[0.1250, 0.5556],
        [1.1667, 0.3333]])

**Special Arrays**

In [34]:
torch.ones((2, 1))

tensor([[1.],
        [1.]])

In [35]:
torch.zeros((3, 4, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [36]:
torch.eye(5, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [37]:
torch.full([4, 3], fill_value=2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

**Random Arrays**

In [101]:
torch.manual_seed(12)
torch.rand((4, 3))

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272],
        [0.6373, 0.2421, 0.7312],
        [0.7224, 0.1992, 0.6948]])

In [38]:
torch.manual_seed(12)
torch.randn((4, 3))

tensor([[-0.2138, -1.3780, -0.0546],
        [ 0.4515,  0.7858, -1.0884],
        [-0.5599, -0.9336,  0.0479],
        [-0.0844, -0.1471,  0.7590]])

In [39]:
torch.manual_seed(12)
torch.randint(2, 13, (4, 3))

tensor([[12,  3,  9],
        [11,  2, 10],
        [ 8,  3,  3],
        [10, 11,  2]])

In [98]:
# Create a random permutation of integers from 0 to 9
torch.randperm(10)

tensor([3, 8, 7, 6, 4, 5, 2, 9, 1, 0])

**Indexing & Slicing**

In [40]:
a = torch.randn(12)
a, a[0:1], a[0], a[[0, 2, 7]]

(tensor([-0.5599, -0.9336,  0.0479, -0.0844, -0.1471,  0.7590,  0.1466, -1.0041,
         -0.7882, -0.8074, -0.2957, -0.1462]),
 tensor([-0.5599]),
 tensor(-0.5599),
 tensor([-0.5599,  0.0479, -1.0041]))

In [124]:
a[2:12:2], a[2::2]

(tensor([-1.1413, -1.6453,  1.8908,  0.5526,  1.9144]),
 tensor([-1.1413, -1.6453,  1.8908,  0.5526,  1.9144]))

In [58]:
a = torch.randn(3,5)
a

tensor([[ 0.2805,  1.0472,  1.0210,  0.9056, -0.4245],
        [ 0.8547,  1.4893,  1.0438,  0.3598,  1.0205],
        [-0.4142,  1.1937, -0.3547, -0.2390, -0.1566]])

In [59]:
a[0:3, 2:-1], a[:, 2:-1]

(tensor([[ 1.0210,  0.9056],
         [ 1.0438,  0.3598],
         [-0.3547, -0.2390]]),
 tensor([[ 1.0210,  0.9056],
         [ 1.0438,  0.3598],
         [-0.3547, -0.2390]]))

In [45]:
a[0:2], a[0:2, :]

(tensor([[ 0.3641,  0.4331,  0.5895, -1.2568,  0.4411],
         [-0.2782, -0.2588, -0.4724,  1.0558,  0.5683]]),
 tensor([[ 0.3641,  0.4331,  0.5895, -1.2568,  0.4411],
         [-0.2782, -0.2588, -0.4724,  1.0558,  0.5683]]))

In [46]:
a[::2, 2:]

tensor([[ 0.5895, -1.2568,  0.4411],
        [ 1.9573, -0.3660, -0.2266]])

In [51]:
a = torch.randn(4, 6, 7)
a

tensor([[[ 4.2969e-01,  1.1980e+00, -1.0833e+00,  3.5402e-01,  7.9477e-01,
           2.3819e+00, -3.7064e-01],
         [-7.9222e-01, -8.3236e-01, -3.2613e-01,  1.7579e+00,  3.6650e-01,
          -3.3034e-02, -1.3126e+00],
         [-9.2532e-01, -3.8545e-01, -5.3512e-01,  4.0278e-01,  1.1849e-01,
           2.9048e+00,  1.4602e+00],
         [ 1.5539e+00, -1.5911e+00, -2.1023e-01, -9.3761e-01,  5.8109e-01,
          -2.9350e-01, -8.0874e-01],
         [-3.1397e-01, -1.9417e+00, -1.8543e+00,  2.7558e-01, -5.9811e-01,
          -3.8076e-01,  3.5677e-03],
         [ 2.4633e-01,  1.3368e-01, -1.0755e+00,  1.9913e+00, -1.4785e+00,
          -1.3697e+00, -5.6596e-01]],

        [[ 1.1672e+00, -1.7709e+00, -4.4624e-01,  7.9434e-01,  7.4588e-01,
           3.8383e-01,  4.3685e-01],
         [ 8.1806e-01, -1.0156e+00, -5.4061e-01,  1.5879e-01, -4.2923e-01,
           4.3937e-01, -1.3256e-01],
         [ 1.7277e+00,  9.3084e-01,  1.4519e+00, -4.9755e-01,  6.5133e-01,
          -2.1107e-01,  2.7

In [54]:
a[1:2, 3:5, 2:4], a[[1], 3:5, 2:4], a[1, 3:5, 2:4]

(tensor([[[ 0.8959,  2.1258],
          [ 0.3422, -2.3196]]]),
 tensor([[[ 0.8959,  2.1258],
          [ 0.3422, -2.3196]]]),
 tensor([[ 0.8959,  2.1258],
         [ 0.3422, -2.3196]]))

In [56]:
a[1], a[:, :, -1], a[..., -1]

(tensor([[ 1.1672, -1.7709, -0.4462,  0.7943,  0.7459,  0.3838,  0.4369],
         [ 0.8181, -1.0156, -0.5406,  0.1588, -0.4292,  0.4394, -0.1326],
         [ 1.7277,  0.9308,  1.4519, -0.4976,  0.6513, -0.2111,  0.2740],
         [-1.1969, -0.6086,  0.8959,  2.1258, -0.0277,  0.3838, -1.7151],
         [ 0.4147,  0.8398,  0.3422, -2.3196,  0.7623,  0.6204,  0.2301],
         [-1.7236,  0.7523, -0.5669,  0.7961, -0.3546, -1.5467,  0.5208]]),
 tensor([[-0.3706, -1.3126,  1.4602, -0.8087,  0.0036, -0.5660],
         [ 0.4369, -0.1326,  0.2740, -1.7151,  0.2301,  0.5208],
         [ 0.6081,  1.2861,  0.9130, -0.4712,  0.0920,  1.1607],
         [ 1.1845, -0.2007, -0.2161,  0.1180,  1.2937,  0.7572]]),
 tensor([[-0.3706, -1.3126,  1.4602, -0.8087,  0.0036, -0.5660],
         [ 0.4369, -0.1326,  0.2740, -1.7151,  0.2301,  0.5208],
         [ 0.6081,  1.2861,  0.9130, -0.4712,  0.0920,  1.1607],
         [ 1.1845, -0.2007, -0.2161,  0.1180,  1.2937,  0.7572]]))

**Unsqueeze & unsqueeze**

In [71]:
# Removing all singleton dimensions
tensor_a = torch.randn(1, 3, 1, 4, 1)
print("Original shape of tensor_a:", tensor_a.shape)  # Output: torch.Size([1, 3, 1, 4, 1])

tensor_b = tensor_a.squeeze()
print("Squeezed shape of tensor_b:", tensor_b.shape)  # Output: torch.Size([3, 4])

Original shape of tensor_a: torch.Size([1, 3, 1, 4, 1])
Squeezed shape of tensor_b: torch.Size([3, 4])


In [104]:
# Removing a specific singleton dimension
a = torch.randn(2, 1, 3, 1, 4)
print("Original shape of a:", a.shape)  # Output: torch.Size([2, 1, 3, 1, 4])

# Remove the first dimension (index 0) which is not 1, so no change is done; Output: torch.Size([2, 1, 3, 1, 4])
print(f"{a.squeeze(0).shape = }")

# Remove the second dimension (index 1) which is size 1; Output: torch.Size([2, 3, 1, 4])
print(f"{a.squeeze(1).shape = }")

# Remove the fourth dimension (index 3) which is size 1; Output: torch.Size([2, 1, 3, 4])
print(f"{a.squeeze(3).shape = }")

print(f"{a.squeeze().shape = }")

Original shape of a: torch.Size([2, 1, 3, 1, 4])
a.squeeze(0).shape = torch.Size([2, 1, 3, 1, 4])
a.squeeze(1).shape = torch.Size([2, 3, 1, 4])
a.squeeze(3).shape = torch.Size([2, 1, 3, 4])
a.squeeze().shape = torch.Size([2, 3, 4])


In [103]:
b = torch.randn(2, 2)
print("Original:", b)  # Output: torch.Size([3, 4])

# Add dimension at the beginning (index 0); # Output: torch.Size([1, 3, 4])
print(f"{b.unsqueeze(0) = } --> {b.unsqueeze(0).shape = }")
# Add dimension in between the two dimensions (index 1); Output: torch.Size([3, 1, 4])
print(f"{b.unsqueeze(1) = } --> {b.unsqueeze(1).shape = }")

# Add dimension at the end (index 2); Output: torch.Size([3, 4, 1])
print(f"{b.unsqueeze(2) = } --> {b.unsqueeze(2).shape = }")

Original: tensor([[ 0.8279,  1.1309],
        [-0.8629,  2.1094]])
b.unsqueeze(0) = tensor([[[ 0.8279,  1.1309],
         [-0.8629,  2.1094]]]) --> b.unsqueeze(0).shape = torch.Size([1, 2, 2])
b.unsqueeze(1) = tensor([[[ 0.8279,  1.1309]],

        [[-0.8629,  2.1094]]]) --> b.unsqueeze(1).shape = torch.Size([2, 1, 2])
b.unsqueeze(2) = tensor([[[ 0.8279],
         [ 1.1309]],

        [[-0.8629],
         [ 2.1094]]]) --> b.unsqueeze(2).shape = torch.Size([2, 2, 1])
