A tensor is a multi-dimensional array of numerical values. Tensor computation (like numpy) with strong GPU acceleration.<br/>

**1️⃣ N-d Tensor:**
- `0-dimensional (Scalar):` A single number, e.g., 5, 3.14, -10. A <font color='red'><b>scalar</b></font> is a single number and in tensor-speak it's a zero dimension tensor.
- `1-dimensional (Vector):` A list of numbers, e.g., [1, 2, 3]. A <font color='blue'><b>vector</b></font> is a single dimension tensor but can contain many numbers.<br/>
- `2-dimensional (Matrix):` A table of numbers, e.g., [[1, 2], [3, 4]]. <font color='green'><b>MATRIX</b></font>  has two dimensions.
- `3-dimensional (or higher):` Like a "cube" of numbers or more complex higher-dimensional structures. These are common for representing images, videos, and more.

**2️⃣ Tensor datatypes:**<br/>
There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types). Some are specific for CPU and some are better for GPU.<br/>
Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).<br/>
The most common type (and generally the default) is `torch.float32` or `torch.float`.<br/>

**3️⃣Getting information from tensors:**<br/>
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

**4️⃣ Math Operations:**<br/>
* Addition ⇒ `a+b `or `torh.add(a, b)`
* Substraction ⇒ `a-b `or `torh.sub(a, b)`
* Multiplication (element-wise) ⇒ `a*b `
* Division ⇒ `a/b `or `torh.div(a, b)`
* Matrix multiplication ⇒ "`@`" in Python is the symbol for matrix multiplication. [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) or [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html)

In [3]:
import torch  #  torch.__version__  -> '2.5.1+cpu'

**1️⃣ Scalar, Vector, Column vector, Matrix, & N-d Tensor**


In [4]:
# Creating a 0D tensor (Scalar)
torch.tensor(4/3)

tensor(1.3333)

In [5]:
# Creating a 1D tensor (Vector)
a = torch.tensor([1, 2, 3])
print(f"{a = } --> {a.__class__ = }")

a = tensor([1, 2, 3]) --> a.__class__ = <class 'torch.Tensor'>


In [6]:
# Creating a 2D tensor (Column vector)
torch.tensor([[1], [2], [3], [4]])

tensor([[1],
        [2],
        [3],
        [4]])

In [7]:
# Creating a 2D tensor (Matrix)
torch.tensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
# Creating a 3D tensor
torch.tensor(
    [[[1, 2, 2 , 5],
      [3, 4, 0 , 8]],

     [[5, 6, 6, 7],
      [4, 8, 1, 2]],

     [[1, 1, 8, 9],
      [0, 0, 2, 3]]]
    )

tensor([[[1, 2, 2, 5],
         [3, 4, 0, 8]],

        [[5, 6, 6, 7],
         [4, 8, 1, 2]],

        [[1, 1, 8, 9],
         [0, 0, 2, 3]]])

In [12]:
# Creating a 4D tensor (Matrix)
torch.tensor(
    [[[[1, 2, 5, 4],
       [3, 4, 1, 0]],
      [[5, 6, 2, 3],
       [7, 8, 6, 4]]],
     [[[9, 10, 0, 9],
       [11, 12, 5, 3]],
      [[13, 14, 8, 7],
       [15, 16, 2, 3]]]]
    )

tensor([[[[ 1,  2,  5,  4],
          [ 3,  4,  1,  0]],

         [[ 5,  6,  2,  3],
          [ 7,  8,  6,  4]]],


        [[[ 9, 10,  0,  9],
          [11, 12,  5,  3]],

         [[13, 14,  8,  7],
          [15, 16,  2,  3]]]])

In [21]:
import torch

# Method 1: Using torch.rand() to create a tensor with random values

# Define the dimensions of the tensor
shape = (1, 1, 2, 5, 6)  # This defines a 5D tensor of 2x3x4x5x6 elements.

# Create a tensor with random numbers between 0 and 1
tensor_5d_random = torch.rand(shape)

print("Random 5D tensor:")
print(tensor_5d_random)
print("Shape of the random tensor:", tensor_5d_random.shape)
print("Number of elements in the tensor:", tensor_5d_random.numel())

Random 5D tensor:
tensor([[[[[0.7814, 0.0994, 0.5195, 0.7621, 0.9517, 0.9682],
           [0.4284, 0.3026, 0.0342, 0.8877, 0.0240, 0.1135],
           [0.5707, 0.1353, 0.6982, 0.2232, 0.6365, 0.8410],
           [0.4357, 0.0819, 0.6638, 0.0124, 0.2257, 0.6444],
           [0.9113, 0.4437, 0.6845, 0.3286, 0.7790, 0.2403]],

          [[0.7459, 0.3484, 0.0972, 0.4612, 0.7812, 0.7169],
           [0.3778, 0.2016, 0.3002, 0.4857, 0.2817, 0.5033],
           [0.5959, 0.1589, 0.2108, 0.3644, 0.0174, 0.6233],
           [0.2189, 0.4498, 0.7410, 0.2308, 0.7776, 0.3275],
           [0.3772, 0.5334, 0.2030, 0.1040, 0.6260, 0.3425]]]]])
Shape of the random tensor: torch.Size([1, 1, 2, 5, 6])
Number of elements in the tensor: 60


In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([1.0, 5.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [198]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0797, 0.3250, 0.4473, 0.5866],
        [0.6251, 0.5120, 0.5415, 0.3856],
        [0.5582, 0.9932, 0.1364, 0.7023]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [194]:
# Creating a 0D tensor (Scalar)
a = torch.tensor(4/3, dtype=torch.float64, device="cpu")
print(f"{a = } --> {a.shape = } --> {a.ndim = } --> {a.size() = }")
a.type(torch.float16)  # Convert into float16 or a.short()

a = tensor(1.3333, dtype=torch.float64) --> a.shape = torch.Size([]) --> a.ndim = 0 --> a.size() = torch.Size([])


tensor(1.3330, dtype=torch.float16)

In [192]:
# Creating a 1D tensor (Vector)
a = torch.tensor([1, 2, 3])
print(f"{a = } --> {a.shape = } --> {a.ndim = } --> {a.size() = }\n{a.__class__ = }")

a = tensor([1, 2, 3]) --> a.shape = torch.Size([3]) --> a.ndim = 1 --> a.size() = torch.Size([3])
a.__class__ = <class 'torch.Tensor'>


In [88]:
# Creating a 2D tensor (Column vector)
a = torch.tensor([[1], [2], [3], [4]])
print(f"{a = }\n{a.shape = } --> {a.ndim = } --> {a.size() = }")

a = tensor([[1],
        [2],
        [3],
        [4]])
a.shape = torch.Size([4, 1]) --> a.ndim = 2 --> a.size() = torch.Size([4, 1])


In [89]:
# Creating a 2D tensor (Matrix)
a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
print(f"{a = }\n{a.shape = } --> {a.ndim = } --> {a.size() = }")

a.numpy()

a = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
a.shape = torch.Size([3, 3]) --> a.ndim = 2 --> a.size() = torch.Size([3, 3])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [44]:
a = tuple([(1, 2), (3, 4), (5, 6)])
torch.tensor(a)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [90]:
# Creating a 3D tensor
a = torch.tensor(
    [[[1, 2],
      [3, 4]],

     [[5, 6],
      [4, 8]],

     [[1, 1],
      [0, 0]]]
    )
print(f"{a = }\n{a.shape = } --> {a.ndim = } --> {a.size() = }")

a = tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [4, 8]],

        [[1, 1],
         [0, 0]]])
a.shape = torch.Size([3, 2, 2]) --> a.ndim = 3 --> a.size() = torch.Size([3, 2, 2])


In [91]:
# Creating a 2D tensor (Matrix)
a = torch.tensor(
    [[[[1, 2],
       [3, 4]],
      [[5, 6],
       [7, 8]]],
     [[[9, 10],
       [11, 12]],
      [[13, 14],
       [15, 16]]]]
    )
print(f"{a = }\n{a.shape = } --> {a.ndim = } --> {a.size() = }")

a = tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
a.shape = torch.Size([2, 2, 2, 2]) --> a.ndim = 4 --> a.size() = torch.Size([2, 2, 2, 2])


**Tensor Attributes and Methods**

In [57]:
#  Mean, std
a = torch.tensor([1, 2, 3])
a.float().mean(), a.type(torch.float32).std()

(tensor(2.), tensor(1.))

In [92]:
# Creating a 2D tensor (Matrix)
a = torch.tensor(
    [[[[1, 2],
       [3, 4]],
      [[5, 6],
       [7, 8]]],
     [[[9, 10],
       [11, 12]],
      [[13, 14],
       [15, 16]]]]
    )
a = a.t()
print(f"{a = }\n{a.shape = } --> {a.ndim = } --> {a.size() = }")

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

**Special Arrays**<br/>
Using [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

In [73]:
torch.ones((2, 1))

tensor([[1.],
        [1.]])

In [80]:
torch.zeros((3, 4, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [84]:
torch.eye(5, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [85]:
torch.full([4, 3], fill_value=2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

**Random Arrays**

In [101]:
torch.manual_seed(12)
torch.rand((4, 3)) # Create a 4*3 tensor filled with random numbers from a uniform distribution on the interval [0, 1)

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272],
        [0.6373, 0.2421, 0.7312],
        [0.7224, 0.1992, 0.6948]])

In [103]:
# Create a 4*3 tensor filled with random numbers from a uniform distribution on the interval [0, 1)
torch.manual_seed(12)
torch.randn((4, 3))

tensor([[-0.2138, -1.3780, -0.0546],
        [ 0.4515,  0.7858, -1.0884],
        [-0.5599, -0.9336,  0.0479],
        [-0.0844, -0.1471,  0.7590]])

In [105]:
torch.manual_seed(12)
torch.randint(2, 13, (4, 3))

tensor([[12,  3,  9],
        [11,  2, 10],
        [ 8,  3,  3],
        [10, 11,  2]])

In [98]:
# Create a random permutation of integers from 0 to 9
torch.randperm(10)

tensor([3, 8, 7, 6, 4, 5, 2, 9, 1, 0])

**Indexing & Slicing**

In [122]:
a = torch.randn(12)
a, a[0:1], a[0], a[[0, 2, 7]]

(tensor([ 1.7400,  1.2857, -1.1413, -1.0312, -1.6453,  3.2576,  1.8908,  0.3741,
          0.5526,  0.0421,  1.9144,  0.2466]),
 tensor([1.7400]),
 tensor(1.7400),
 tensor([ 1.7400, -1.1413,  0.3741]))

In [124]:
a[2:12:2], a[2::2]

(tensor([-1.1413, -1.6453,  1.8908,  0.5526,  1.9144]),
 tensor([-1.1413, -1.6453,  1.8908,  0.5526,  1.9144]))

In [132]:
a = torch.randn(3,5)
a

tensor([[ 0.2748,  1.9458, -1.0733,  1.8559, -1.2232],
        [-0.0369,  1.7959,  0.9518, -0.0144,  3.0890],
        [-1.6665, -1.3407,  1.7006, -0.7644,  0.9168]])

In [136]:
a[0:3, 2:-1], a[:, 2:-1], a[0:2], a[0:2, :], a[::2, 2:]

(tensor([[-1.0733,  1.8559],
         [ 0.9518, -0.0144],
         [ 1.7006, -0.7644]]),
 tensor([[-1.0733,  1.8559],
         [ 0.9518, -0.0144],
         [ 1.7006, -0.7644]]),
 tensor([[ 0.2748,  1.9458, -1.0733,  1.8559, -1.2232],
         [-0.0369,  1.7959,  0.9518, -0.0144,  3.0890]]),
 tensor([[ 0.2748,  1.9458, -1.0733,  1.8559, -1.2232],
         [-0.0369,  1.7959,  0.9518, -0.0144,  3.0890]]),
 tensor([[-1.0733,  1.8559, -1.2232],
         [ 1.7006, -0.7644,  0.9168]]))

In [139]:
a = torch.randn(4, 6, 7)
a

tensor([[[-0.6703,  1.4412, -0.1533, -0.8794, -0.5423, -0.0420, -0.2877],
         [-0.2922,  0.7157,  0.7119, -0.9787, -1.6856,  0.4466,  2.2946],
         [-0.8751, -0.1290, -1.2842,  0.2086, -0.6043, -0.2626,  0.8952],
         [ 1.3979, -2.2215,  0.4134, -0.0226,  0.1649, -0.8611, -0.7836],
         [-1.1848,  1.2251,  0.5372, -0.4704,  1.2422,  0.8005,  1.2001],
         [-1.5673, -0.7892, -0.2722,  0.6104,  1.8975,  0.4636, -0.3487]],

        [[ 0.7788, -0.4777, -1.9169, -0.2125,  0.8114,  0.5700, -0.5149],
         [-1.3312, -1.5866, -0.5796,  0.1399,  0.6590,  0.5294, -0.6222],
         [-0.7204, -0.6582, -1.4321,  0.5743,  1.0892, -1.5107, -0.6150],
         [ 0.5099, -1.2288,  0.0390, -0.3312,  1.5377, -0.3099,  0.6083],
         [ 0.3750, -0.0359,  0.1439,  2.3967,  0.7019, -1.4175, -0.1454],
         [ 1.0030,  1.6245,  0.7386,  0.3521,  0.8626, -0.7893, -1.1969]],

        [[-0.1089, -0.4277,  0.4336,  0.3443, -0.4808, -1.5701,  0.3897],
         [ 0.6531, -0.5157,  0.350

In [ ]:
a[1:2, 3:5, 2:4], a[[1], 3:5, 2:4], a[1, 3:5, 2:4], a[1:3, :, -1]

(tensor([[[ 0.0390, -0.3312],
          [ 0.1439,  2.3967]]]),
 tensor([[[ 0.0390, -0.3312],
          [ 0.1439,  2.3967]]]),
 tensor([[ 0.0390, -0.3312],
         [ 0.1439,  2.3967]]),
 tensor([[-0.5149, -0.6222, -0.6150,  0.6083, -0.1454, -1.1969],
         [ 0.3897, -0.3823,  0.4449,  1.6617, -0.7075, -0.4852]]),
 tensor([[ 0.7788, -0.4777, -1.9169, -0.2125,  0.8114,  0.5700, -0.5149],
         [-1.3312, -1.5866, -0.5796,  0.1399,  0.6590,  0.5294, -0.6222],
         [-0.7204, -0.6582, -1.4321,  0.5743,  1.0892, -1.5107, -0.6150],
         [ 0.5099, -1.2288,  0.0390, -0.3312,  1.5377, -0.3099,  0.6083],
         [ 0.3750, -0.0359,  0.1439,  2.3967,  0.7019, -1.4175, -0.1454],
         [ 1.0030,  1.6245,  0.7386,  0.3521,  0.8626, -0.7893, -1.1969]]))

In [153]:
a[1], a[:, :, -1], a[..., -1]

(tensor([[ 0.7788, -0.4777, -1.9169, -0.2125,  0.8114,  0.5700, -0.5149],
         [-1.3312, -1.5866, -0.5796,  0.1399,  0.6590,  0.5294, -0.6222],
         [-0.7204, -0.6582, -1.4321,  0.5743,  1.0892, -1.5107, -0.6150],
         [ 0.5099, -1.2288,  0.0390, -0.3312,  1.5377, -0.3099,  0.6083],
         [ 0.3750, -0.0359,  0.1439,  2.3967,  0.7019, -1.4175, -0.1454],
         [ 1.0030,  1.6245,  0.7386,  0.3521,  0.8626, -0.7893, -1.1969]]),
 tensor([[-0.2877,  2.2946,  0.8952, -0.7836,  1.2001, -0.3487],
         [-0.5149, -0.6222, -0.6150,  0.6083, -0.1454, -1.1969],
         [ 0.3897, -0.3823,  0.4449,  1.6617, -0.7075, -0.4852],
         [-0.4320, -0.0752, -0.3669,  0.5602,  1.3068, -0.3125]]),
 tensor([[-0.2877,  2.2946,  0.8952, -0.7836,  1.2001, -0.3487],
         [-0.5149, -0.6222, -0.6150,  0.6083, -0.1454, -1.1969],
         [ 0.3897, -0.3823,  0.4449,  1.6617, -0.7075, -0.4852],
         [-0.4320, -0.0752, -0.3669,  0.5602,  1.3068, -0.3125]]))

**Math Operations (Addition, Subtraction, Multiplication, Division, Matrix Multiplication)**
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [168]:
a = torch.randint(10, (2, 2))
b = torch.randint(10, (2, 2))
torch.add(a, b, ), torch.sub(a, b, ), a * b, a / b, a @ b, torch.matmul(a, b)

(tensor([[13,  5],
         [17, 18]]),
 tensor([[-3, -5],
         [ 1,  0]]),
 tensor([[40,  0],
         [72, 81]]),
 tensor([[0.6250, 0.0000],
         [1.1250, 1.0000]]),
 tensor([[ 40,  25],
         [144, 126]]),
 tensor([[ 40,  25],
         [144, 126]]))

In [178]:
a = torch.randint(10, (2, 2))
a, a.shape, a.unsqueeze(0), a.unsqueeze(0).shape, a.unsqueeze(1), a.unsqueeze(1).shape, a.unsqueeze(2), a.unsqueeze(2).shape

(tensor([[9, 7],
         [9, 9]]),
 torch.Size([2, 2]),
 tensor([[[9, 7],
          [9, 9]]]),
 torch.Size([1, 2, 2]),
 tensor([[[9, 7]],
 
         [[9, 9]]]),
 torch.Size([2, 1, 2]),
 tensor([[[9],
          [7]],
 
         [[9],
          [9]]]),
 torch.Size([2, 2, 1]))

In [185]:
a.squeeze(0), a.squeeze(1)

(tensor([[9, 7],
         [9, 9]]),
 tensor([[9, 7],
         [9, 9]]))