**Welcome to Deep Learning with Keras and TensorFlow in Python**

**Presented by: Reza Saadatyar (2024-2025)**<br/>
**E-mail: Reza.Saadatyar@outlook.com**

TensorFlow is a framework for building and running machine learning models using tensors.<br/>
A tensor generalizes vectors and matrices to higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base data types.<br/>

▪ Command (run in terminal, not Python): `pip install tensorflow`<br/>
▪ GPU version: `pip install tensorflow-gpu`<br/>

In TensorFlow, code can be executed in two primary modes: `Eager Execution` and `Graph Execution`. These modes determine how operations are processed and optimized, which can impact performance, debugging, and deployment.<br/>

**Eager Execution** in TensorFlow 2.x is an imperative mode where operations execute instantly without a computational graph, offering an interactive, Python-like coding experience. Eager execution is enabled by default.<br/>

`Advantages:`<br/>
▪ Simplifies debugging with tools like print() or a debugger.<br/> 
▪ Great for rapid prototyping and experimentation.<br/>
▪ Eliminates the need to build graphs or sessions manually.<br/>

`Disadvantages:`<br/>
▪ Less efficient for large-scale or production use due to lack of graph optimization.<br/>
▪ Not suitable for hardware relying on static graphs (e.g., TensorFlow Lite, TensorFlow Serving).<br/>

**Graph Execution** builds a computational graph of operations, compiles it, and executes it as a whole. Default in TensorFlow 1.x, it’s still usable in TensorFlow 2.x by disabling eager execution or using specific APIs. Instead of running operations immediately, TensorFlow creates a graph of nodes (operations) and edges (tensors), optimizes it (e.g., removing redundancies or fusing operations), and executes it in a tf.Disable eager execution to use graph mode → `tf.compat.v1.disable_eager_execution()` or the `tf.function decorator` to convert eager code into a graph.
<br/>

`Advantages:`<br/>
▪ Optimized for performance on GPUs/TPUs via graph optimizations.<br/>
▪ Ideal for production deployment needing static graphs (e.g., mobile, servers).<br/> 
▪ Supports distributed computing and automatic gradient computation.<br/>

`Disadvantages:`<br/>
▪ Debugging is harder as operations run only when the graph executes.<br/>
▪ Requires session management and explicit data feeding, which is less intuitive.<br/>

**TensorFlow Outline:**<br/>
▪ CPU (Central Processing Unit) & GPU (Graphics Processing Unit)<br/>
▪ Scalar, Vector, Column Vector, Matrix, & N-d Tensor<br/>
▪ Getting information from tensors<br/>
▪ Math Operations<br/>
▪ Special Arrays<br/>
▪ Random Arrays<br/>
▪ Indexing & Slicing<br/>
▪ Unsqueeze & squeeze<br/>
▪ TensorFlow Tensors & NumPy<br/>
▪ Array Manipulation<br/>

<font color='#FF000e' size="4.5" face="Arial"><b>Import modules</b></font>

In [44]:
import pprint
import numpy as np
import tensorflow as tf

print(f'TensorFlow Version: {tf.__version__}')

TensorFlow Version: 2.18.0


<font color=#f3dc08 size="4.5" face="Arial"><b>1️⃣ CPU (Central Processing Unit) & GPU (Graphics Processing Unit)</b></font><br/>
`CPU:`<br/>
▪ Designed for general-purpose computing.<br/>
▪ Optimized for sequential tasks.<br/>
▪ Has a few powerful cores.<br/>
▪ Excellent at handling complex logic and single-threaded applications.<br/>
  
`GPU:`<br/>
▪ Designed for parallel processing.<br/>
▪ Has thousands of smaller, less powerful cores.<br/>
▪ GPUs offer far faster numerical computing than CPUs.<br/>
▪ Optimized for tasks that can be divided into many independent calculations.<br/>
▪ Excellent for tasks like matrix operations, which are common in deep learning.<br/> 

In [41]:
# To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means
# "run this on the command line".
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [46]:
# Check GPU availability by listing physical devices and checking if any GPU is present
print(f"GPU Available: {tf.config.list_physical_devices('GPU') != []}")
# Example output: GPU Available: False (if no GPU is detected)

# Set the device to GPU if available, otherwise fallback to CPU
device = '/GPU:0' if tf.config.list_physical_devices('GPU') else '/CPU:0'
# Print the device being used for computation
print(f"Using device: {device}")

GPU Available: False
Using device: /CPU:0


<font color=#08f308 size="4.5" face="Arial"><b>2️⃣ Scalar, Vector, Column Vector, Matrix, & N-d Tensor</b></font><br/>
A tensor is a multi-dimensional array of numerical values. Tensor computation (like numpy) with strong GPU acceleration.<br/>
▪ `0-dimensional (Scalar):` A single number, e.g., 5, 3.14, -10. A <font color='red'><b>scalar</b></font> is a single number and in tensor-speak it's a zero dimension tensor.<br/>
▪ `1-dimensional (Vector):` A list of numbers, e.g., [1, 2, 3]. A <font color='blue'><b>vector</b></font> is a single dimension tensor but can contain many numbers.<br/>
▪ `2-dimensional (Matrix):` A table of numbers, e.g., [[1, 2], [3, 4]]. <font color='green'><b>MATRIX</b></font>  has two dimensions.<br/>
▪ `3-dimensional (or higher):` Like a "cube" of numbers or more complex higher-dimensional structures. These are common for representing images, videos, and more.<br/>

In [47]:
# Create a scalar (0-dimensional tensor) with a constant value of 4/3 and specify its data type as float32
scalar = tf.constant(4/3, dtype=tf.float32)
# Print the scalar tensor
print(f"Scalar: {scalar}")

Scalar: 1.3333333730697632


In [48]:
# Create a vector (1-dimensional tensor) with a list of values [1, 2, 3]
vector = tf.constant([1, 2, 3])
# Print the vector tensor and its class type
print(f"Vector: {vector} --> {vector.__class__ = }")

# Create a column vector (2-dimensional tensor) with a nested list of values [[1], [2], [3], [4]]
col_vector = tf.constant([[1], [2], [3], [4]])
# Print the column vector tensor
print(f"Column Vector:\n{col_vector}")

Vector: [1 2 3] --> vector.__class__ = <class 'tensorflow.python.framework.ops.EagerTensor'>
Column Vector:
[[1]
 [2]
 [3]
 [4]]


In [49]:
# Create a matrix (2-dimensional tensor) with a nested list of values [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Print the matrix tensor
print(f"Matrix:\n{matrix}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
# Create a 3D tensor (3-dimensional tensor) with a nested list of values
# The structure is: 3 layers, each containing 2 rows and 4 columns
tensor_3d = tf.constant([[[1, 2, 2, 5], [3, 4, 0, 8]],
                         [[5, 6, 6, 7], [4, 8, 1, 2]],
                         [[1, 1, 8, 9], [0, 0, 2, 3]]])
# Print the 3D tensor
print(f"3D Tensor:\n{tensor_3d}")

3D Tensor:
[[[1 2 2 5]
  [3 4 0 8]]

 [[5 6 6 7]
  [4 8 1 2]]

 [[1 1 8 9]
  [0 0 2 3]]]


In [ ]:
# Create a 4D tensor (4-dimensional tensor) with a deeply nested list of values
# The structure is: 1 batch, 2 layers, each containing 2 rows and 4 columns
tensor_4d = tf.constant([[[[1, 2, 5, 4], [3, 4, 1, 0]],
                          [[5, 6, 2, 3], [7, 8, 6, 4]]]])
# Print the 4D tensor
print(f"4D Tensor:\n{tensor_4d}")

4D Tensor:
[[[[1 2 5 4]
   [3 4 1 0]]

  [[5 6 2 3]
   [7 8 6 4]]]]


In [51]:
# Create a tensor from a tuple of tuples
# The outer tuple contains inner tuples, each representing a row in the tensor
tensor_a = tf.constant([(1, 2), (3, 4), (5, 6)])
# Print the tensor created from the tuple
print(f"\nTensor from tuple:\n{tensor_a}")


Tensor from tuple:
[[1 2]
 [3 4]
 [5 6]]


<font color=#2b08f3 size="4.5" face="Arial"><b>3️⃣ Getting information from tensors</b></font><br/>
▪ `shape` - what shape is the tensor? (some operations require specific shape rules)<br/>
▪ `dtype` - what datatype are the elements within the tensor stored in?<br/>
▪ `device` - what device is the tensor stored on? (usually GPU or CPU)<br/>

**🔸 Tensor datatypes**<br/>
There are many different tensor datatypes available in TensorFlow. Some are specific for CPU and some are better for GPU. Generally, if you see `tf.device('/GPU:0')` anywhere, the tensor is being used for GPU (since NVIDIA GPUs use a computing toolkit called CUDA). The most common type (and generally the default) is `tf.float32`.

In [53]:
# Create a tensor with default dtype (float32) and print its dtype and device
float_32_tensor = tf.constant([1.0, 5.0, 6.0])
print(f"Dtype: {float_32_tensor.dtype}, Device: {float_32_tensor.device}")

# Create a scalar tensor with explicit dtype (float64) and an empty shape (scalar)
tensor = tf.constant(4/3, dtype=tf.float64, shape=())
# Pretty-print tensor details: value, shape, rank, and size
pprint.pprint(f"{tensor = } --> {tensor.shape = }, {tf.rank(tensor) = }, {tf.size(tensor) = }")

# Change the dtype of the tensor from float64 to float16 using tf.cast
tensor_float16 = tf.cast(tensor, tf.float16)
# Print the new tensor with float16 dtype
print(f"\nFloat16 tensor: {tensor_float16}")

Dtype: <dtype: 'float32'>, Device: /job:localhost/replica:0/task:0/device:CPU:0
('tensor = <tf.Tensor: shape=(), dtype=float64, numpy=1.3333333333333333> --> '
 'tensor.shape = TensorShape([]), tf.rank(tensor) = <tf.Tensor: shape=(), '
 'dtype=int32, numpy=0>, tf.size(tensor) = <tf.Tensor: shape=(), dtype=int32, '
 'numpy=1>')

Float16 tensor: 1.3330078125


<font color=#f308ad size="4.5" face="Arial"><b>4️⃣ Math Operations</b></font><br/>
▪ `Addition` ⇒ *a+b* or *tf.add(a, b)*<br/>
▪ `Substraction` ⇒ *a-b* or *tf.subtract(a, b)*<br/>
▪ `Multiplication (element-wise)` ⇒ *axb* or *tf.multiply(a, b)*<br/>
▪ `Division` ⇒ *a/b* or *tf.divide(a, b)*<br/>
▪ `Matrix multiplication` ⇒ *tf.matmul(a, b)*<br/>
▪ `tf.reduce_mean & tf.math.reduce_std`

In [58]:
# Define two 2x2 tensors 'a' and 'b'
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Perform element-wise addition
add_result = a + b
print(f"Addition:\n{add_result}")

# Perform element-wise subtraction
sub_result = a - b
print(f"\nSubtraction:\n{sub_result}")

# Perform element-wise multiplication
mul_result = a * b
print(f"\nElement-wise Multiplication:\n{mul_result}")

# Perform element-wise division
div_result = a / b
print(f"\nDivision:\n{div_result}")

# Perform matrix multiplication (dot product) using tf.matmul
matmul_result = tf.matmul(a, b)
print(f"\nMatrix Multiplication:\n{matmul_result}")

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Matrix Multiplication:
[[19 22]
 [43 50]]


In [ ]:
# Define a 2x2 tensor with float values
tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# Calculate the mean of all elements in the tensor
mean_all = tf.reduce_mean(tensor)

# Calculate the mean along dimension 0 (columns)
mean_dim0 = tf.reduce_mean(tensor, axis=0)

# Calculate the mean along dimension 1 (rows)
mean_dim1 = tf.reduce_mean(tensor, axis=1)
# Print the mean values
print(f"Mean all: {mean_all}")
print(f"Mean dim 0: {mean_dim0}")
print(f"Mean dim 1: {mean_dim1}")

# Calculate the standard deviation of all elements in the tensor
# Ensure the tensor is cast to float32 for compatibility with tf.math.reduce_std
std_all = tf.math.reduce_std(tf.cast(tensor, tf.float32))
# Print the standard deviation
print(f"Std all: {std_all}")

Mean all: 2.5
Mean dim 0: [2. 3.]
Mean dim 1: [1.5 3.5]
Std all: 1.1180340051651


<font color=#08e3f3 size="4.5" face="Arial"><b>5️⃣ Special Arrays</b></font><br/>
▪ `ones`<br/>
▪ `zeros`<br/>
▪ `eye`<br/>
▪ `fill`<br/>
▪ `arange`<br/>
▪ `reshape`<br/>
▪ `linspace`<br/>

🔸 Using `tf.zeros_like(input)` or `tf.ones_like(input)` which return a tensor filled with zeros or ones in the same shape as the input, respectively.

In [61]:
# Create a tensor of ones with shape [2, 1] (2 rows, 1 column)
ones = tf.ones([2, 1])
print(f"Ones:\n{ones}")

# Create a tensor of zeros with shape [3, 4, 3] (3 layers, 4 rows, 3 columns)
zeros = tf.zeros([3, 4, 3])
print(f"\nZeros:\n{zeros}")

# Create an identity matrix (eye) with 5 rows and 4 columns
eye = tf.eye(5, num_columns=4)
print(f"\nEye:\n{eye}")

# Create a tensor filled with the value 2 and shape [4, 3] (4 rows, 3 columns)
full = tf.fill([4, 3], 2)
print(f"\nFull:\n{full}")

# Create a tensor with values from 0 to 9 (exclusive) using tf.range
arange = tf.range(10)
print(f"\nArange: {arange}")

# Reshape a tensor with values from 0 to 5 into a 2x3 matrix
tensor = tf.range(6)
reshaped = tf.reshape(tensor, [2, 3])
print(f"\nReshaped:\n{reshaped}")

# Create a tensor with 5 evenly spaced values between 0.0 and 1.0 using tf.linspace
linspace = tf.linspace(0.0, 1.0, 5)
print(f"\nLinspace: {linspace}")

Ones:
[[1.]
 [1.]]

Zeros:
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

Eye:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Full:
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]

Arange: [0 1 2 3 4 5 6 7 8 9]

Reshaped:
[[0 1 2]
 [3 4 5]]

Linspace: [0.   0.25 0.5  0.75 1.  ]


<font color=#98c007 size="4.5" face="Arial"><b>6️⃣ Random Arrays</b></font><br/>
▪ `tf.random.uniform(shape, minval=0, maxval=1): or torch.randint` Create an n x m tensor filled with random numbers from a uniform distribution on the interval [0, 1).<br/>
▪ `tf.random.normal(shape, mean=0, stddev=1): or torch.randn` Create an n x m tensor filled with random numbers from a normal distribution with mean 0 and variance 1.<br/>
▪ `tf.random.uniform(shape, minval=low, maxval=high, dtype=tf.int32): or torch.rand` Create an n x m tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).<br/>
▪ `tf.random.shuffle(value): or torch.randperm` Create a random permutation of integers from 0 to value.<br/>
▪ `tf.transpose(input, perm): or torch.permute` Permute the original tensor to rearrange the axis order.

In [64]:
# Set a random seed for reproducibility
tf.random.set_seed(12)  # For reproducibility

# Generate a 4x3 tensor with random uniform values between 0 and 1
rand = tf.random.uniform([4, 3], minval=0, maxval=1)

# Print the random uniform tensor
print(f"Random Uniform:\n{rand}")

# Generate a 4x3 tensor with random values from a normal distribution (mean=0, stddev=1)
randn = tf.random.normal([4, 3], mean=0, stddev=1)

# Print the random normal tensor
print(f"\nRandom Normal:\n{randn}")

# Generate a 4x3 tensor with random integers between 2 and 12 (inclusive)
randint = tf.random.uniform([4, 3], minval=2, maxval=13, dtype=tf.int32)

# Print the random integer tensor
print(f"\nRandom Int:\n{randint}")

# Generate a random permutation of numbers from 0 to 9
randperm = tf.random.shuffle(tf.range(10))

# Print the random permutation
print(f"\nRandom Permutation: {randperm}")

# Create a 224x224x3 tensor with random uniform values
original = tf.random.uniform([224, 224, 3])

# Transpose the tensor by permuting dimensions (from [224, 224, 3] to [3, 224, 224])
permuted = tf.transpose(original, perm=[2, 0, 1])

# Print the shape of the original tensor
print(f"\nOriginal shape: {original.shape}")

# Print the shape of the permuted tensor
print(f"\nPermuted shape: {permuted.shape}")

Random Uniform:
[[0.47720265 0.33357763 0.4960823 ]
 [0.48351312 0.2963959  0.69444907]
 [0.68488    0.6662284  0.07551682]
 [0.06608915 0.91428673 0.21982336]]

Random Normal:
[[-1.4789797  -0.29240268  0.07752764]
 [-0.5062714  -0.83865356 -0.09457338]
 [-1.52905    -0.6021644  -0.12325561]
 [ 0.10217136 -1.4168909   1.00783   ]]

Random Int:
[[ 9  8  6]
 [ 5  5 12]
 [ 6  2  7]
 [ 7  2  3]]

Random Permutation: [3 6 5 7 9 2 4 8 0 1]

Original shape: (224, 224, 3)

Permuted shape: (3, 224, 224)


<font color=#8a05b3 size="4.5" face="Arial"><b>7️⃣ Indexing & Slicing</b></font><br/>
▪ `Indexing:` Use integer indices to specify the position of the element you want to retrieve (Accessing individual elements).<br/>
▪ `Slicing:` Slicing allows you to extract a sub-part of your tensor by specifying a range of indices using the colon : operator (Extracting sub-tensors).<br/>
▪ `start:end` (exclusive end)<br/>
▪ `start:` (from start to end of dimension)<br/>
▪ `:end` (from beginning to end of dimension)<br/>
▪ `:` (all elements)<br/>
▪ `start:end:step` (start to end with given step)<br/>

In [65]:
# Create a 2D tensor with random values from a normal distribution (shape [3, 5])
a = tf.random.normal([3, 5])
print(f"a:\n{a}")

# Slice the first 2 rows of the tensor
print(f"\na[0:2]:\n{a[0:2]}")

# Slice every alternate row and columns starting from index 2
print(f"\na[::2, 2:]:\n{a[::2, 2:]}")

# Create a 3D tensor with random values from a normal distribution (shape [4, 6, 7])
a_3d = tf.random.normal([4, 6, 7])
print(f"\na_3d shape: {a_3d.shape}")

# Slice the tensor: take the 2nd layer (index 1), rows 3 to 4 (exclusive), and columns 2 to 3 (exclusive)
print(f"\na_3d[1, 3:5, 2:4]:\n{a_3d[1, 3:5, 2:4]}")

# Slice the tensor: take all layers, all rows, and the last column
print(f"\na_3d[:, :, -1]:\n{a_3d[:, :, -1]}")

a:
[[ 0.5615161  -0.06268908 -1.8762693  -0.4634338   1.5915105 ]
 [-0.28809077  0.42621186 -0.22641563  0.09014436  0.97549963]
 [ 1.0928404   1.4208329  -0.56682575 -0.27064663 -0.9919088 ]]

a[0:2]:
[[ 0.5615161  -0.06268908 -1.8762693  -0.4634338   1.5915105 ]
 [-0.28809077  0.42621186 -0.22641563  0.09014436  0.97549963]]

a[::2, 2:]:
[[-1.8762693  -0.4634338   1.5915105 ]
 [-0.56682575 -0.27064663 -0.9919088 ]]

a_3d shape: (4, 6, 7)

a_3d[1, 3:5, 2:4]:
[[-1.0830227  0.9074694]
 [-1.5599444  1.4935122]]

a_3d[:, :, -1]:
[[ 0.5489658  -0.62722516  1.1423011  -1.6919721  -0.32114342  0.94501936]
 [-0.29095474 -0.93433493  0.16864355 -1.0387399   0.6346906   0.49951598]
 [-0.3861363  -0.70366967 -0.4324873  -0.58843803  0.5453059   0.39490286]
 [ 1.2849358   1.055529   -0.30219096 -0.04969664  0.71300924  0.58408606]]


<font color=#f3084f size="4.5" face="Arial"><b>8️⃣ Unsqueeze & squeeze</b></font><br/>
▪ The `tf.squeeze()` method removes all singleton dimensions from a tensor. It will reduce the number of dimensions by removing the ones that have a size of 1.<br/>
▪ The `tf.expand_dims()` method adds a singleton dimension at a specified position in a tensor. It will increase the number of dimensions by adding a size of 1 dimension at a specific position.

In [66]:
# Create a tensor with shape [1, 3, 1, 4, 1] and random normal values
tensor_a = tf.random.normal([1, 3, 1, 4, 1])
print(f"Original shape: {tensor_a.shape}")

# Remove all dimensions of size 1 using tf.squeeze
tensor_b = tf.squeeze(tensor_a)
print(f"\nSqueezed shape: {tensor_b.shape}")

# Create another tensor with shape [2, 1, 3, 1, 4] and random normal values
a = tf.random.normal([2, 1, 3, 1, 4])
print(f"\nOriginal shape: {a.shape}")

# Remove only the dimension of size 1 at axis 1 using tf.squeeze
print(f"\nSqueeze dim 1: {tf.squeeze(a, axis=1).shape}")

# Create a 2D tensor with shape [2, 2] and random normal values
b = tf.random.normal([2, 2])
print(f"\nOriginal:\n{b}")

# Add a new dimension at axis 0 using tf.expand_dims
print(f"\nUnsqueeze dim 0:\n{tf.expand_dims(b, axis=0)}")

Original shape: (1, 3, 1, 4, 1)

Squeezed shape: (3, 4)

Original shape: (2, 1, 3, 1, 4)

Squeeze dim 1: (2, 3, 1, 4)

Original:
[[-0.08559076  1.1976115 ]
 [ 0.38311407 -1.2576591 ]]

Unsqueeze dim 0:
[[[-0.08559076  1.1976115 ]
  [ 0.38311407 -1.2576591 ]]]


<font color=#7ddbbf size="4.5" face="Arial"><b>9️⃣ TensorFlow Tensors & NumPy</b></font><br/>
▪ `tf.convert_to_tensor(ndarray):` NumPy array → TensorFlow tensor<br/>
▪ `tf.Tensor.numpy():` TensorFlow tensor → NumPy array<br/>

In [ ]:
# Create a NumPy array with values from 1.0 to 7.0
array = np.arange(1.0, 8.0)

# Convert the NumPy array to a TensorFlow tensor
tensor = tf.convert_to_tensor(array)

# Convert the TensorFlow tensor back to a NumPy array
nump = tensor.numpy()

# Print the original NumPy array
print(f"Array: {array}")
# Print the TensorFlow tensor
print(f"Tensor: {tensor}")
# Print the NumPy array converted from the TensorFlow tensor
print(f"NumPy from Tensor: {nump}")

Array: [1. 2. 3. 4. 5. 6. 7.]
Tensor: [1. 2. 3. 4. 5. 6. 7.]
NumPy from Tensor: [1. 2. 3. 4. 5. 6. 7.]


<font color=#f0dc2d size="4.5" face="Arial"><b>🔟 Array Manipulation</b></font><br/>
▪ `tf.stack: or torch.stack` Stacks tensors along a new dimension.<br/>
▪ `tf.concat or torch.cat:` Concatenates tensors along an existing dimension.<br/>
▪ `tf.split or torch.split:` Dividing a tensor into multiple sub-arrays.<br/>
▪ `tf.reshape or torch.flatten:` Compresses a tensor into a contiguous 1D representation.<br/>
▪ `tf.identity or torch.clone:` Creates a deep copy. <br/>
▪ `tf.tile or torch.repeat, torch.tile:` Repeats the tensor along specified dimensions. (Note: TensorFlow uses tf.tile for both repetition scenarios, unlike PyTorch's repeat and tile distinction.)<br/>
▪ `tf.unique or torch.unique:` Finding unique elements in a tensor.<br/>
▪ `tf.sort, tf.argsort or torch.sort, torch.argsort:` Returns both the sorted tensor and the indices of the sorted elements.<br/>
▪ `tf.argmax, tf.argmin or torch.argmax, torch.argmin:` Finding the indices of the maximum and minimum values. For example, tf.argmax() and tf.argmin().<br/>
▪ `tf.where(condition, x, y)`, `tf.args_where`, `tf.nonzero`, `extract(using arr[cond])` or `torch.where`, `torch.args_where:` Conditional operations. tf.where() returns elements based on a condition, tf.nonzero() returns indices of elements that satisfy a condition, and arr[cond] extracts elements based on a condition.

In [ ]:
# Stack two tensors along a new axis (axis=0)
a = tf.random.normal([2, 2])
b = tf.random.normal([2, 2])

stacked = tf.stack([a, b], axis=0)
print(f"Stacked:\n{stacked}")

Stacked:
[[[ 0.52072555  0.7971705 ]
  [-0.8475972  -1.1279716 ]]

 [[ 0.85128456  0.7019337 ]
  [-0.74072427  1.0812322 ]]]


In [69]:
# Concatenate two tensors along an existing axis (axis=1)
concatenated = tf.concat([tf.expand_dims(a, 0), tf.expand_dims(b, 0)], axis=1)
print(f"Concatenated:\n{concatenated}")

Concatenated:
[[[ 0.52072555  0.7971705 ]
  [-0.8475972  -1.1279716 ]
  [ 0.85128456  0.7019337 ]
  [-0.74072427  1.0812322 ]]]


In [70]:
# Split a tensor into multiple tensors along a specified axis (axis=1)
tensor = tf.range(1, 13)
split_tensors = tf.split(tf.reshape(tensor, [3, 4]), num_or_size_splits=2, axis=1)
print(f"Split:\n{split_tensors}")

Split:
[<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 7,  8],
       [11, 12]], dtype=int32)>]


In [73]:
# Flatten a 3D tensor into a 1D tensor
a_3d = tf.reshape(tf.range(1, 25), [3, 2, 4])
print(f'{a_3d = }')
flattened = tf.reshape(a_3d, [-1])
print(f"Flattened:\n{flattened}")

a_3d = <tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>
Flattened:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [72]:
# Create a deep copy (clone) of a tensor using tf.identity
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
cloned = tf.identity(tensor)
print(f"Cloned:\n{cloned}")

Cloned:
[[1 2 3]
 [4 5 6]]


In [74]:
# Repeat (tile) a tensor along a specified axis
tensor = tf.constant([1, 2, 3])
tiled = tf.tile(tensor, [2])
print(f"Tiled: {tiled}")

Tiled: [1 2 3 1 2 3]


In [75]:
# Find unique elements in a tensor
tensor = tf.constant([2, 1, 3, 2, 1])
unique_elements = tf.unique(tensor).y
print(f"Unique: {unique_elements}")

Unique: [2 1 3]


In [76]:
# Sort the elements of a tensor
sorted_tensor = tf.sort(tensor)
print(f"Sorted: {sorted_tensor}")

Sorted: [1 1 2 2 3]


In [77]:
# Get the indices that would sort the tensor
indices = tf.argsort(tensor)
print(f"Argsort indices: {indices}")

Argsort indices: [1 4 0 3 2]


In [84]:
# Find the index of the maximum and minimum value in the tensor
max_idx = tf.argmax(tensor)
min_idx = tf.argmin(tensor)
print(f"Argmax: {max_idx}, \nArgmin: {min_idx}")

Argmax: [1 1 2 2], 
Argmin: [0 2 0 1]


In [ ]:
# Apply a conditional operation using tf.where
tensor = tf.constant([[1, 2, 3, 4], [9, 7, 11, -20], [9, -7, 12, 6]])
print(f"tensor:\n{tensor}")

result = tf.where((tensor >= 3) & (tensor < 10), tensor, -10)
print(f"\nWhere:\n{result}")

tensor:
[[  1   2   3   4]
 [  9   7  11 -20]
 [  9  -7  12   6]]

Where:
[[-10 -10   3   4]
 [  9   7 -10 -10]
 [  9 -10 -10   6]]
